### ISSUE TITLE
Issues in Layers Panel and Canvas Panel

### ISSUE THREAD

**Issue by UmeshRavani98** [dromara/yft-design#100]
When we duplicate a layer. it duplicated properly! but when we select the duplicated layer from layer's panel then it select's both the layers instead of the duplicated one!

Similarly when we add a Canvas and if we delete the canvas then both the canvases gets deleted!

**Comment by more-strive** [comment]
This may be due to duplicate IDs

**Comment by UmeshRavani98** [comment]
How to Fix this Duplicate ID Issue sir?
Same for Duplicate Canvases!

Could you let me know which part of code to modify to resolve this issue
Thankyou

**Comment by more-strive** [comment]
src/hooks/useHandleElement.ts

**Comment by more-strive** [comment]
It has been updated

**Comment by UmeshRavani98** [comment]
Thankyou for the being too fast sir!

Could you resolve the issue of when we delete the object the object deletes from canvas, but not from Layer Panel sir.
