### ISSUE TITLE
导入svg后拖拽svg散开了

### ISSUE THREAD

**Issue by chaoyang915506** [dromara/yft-design#105]
![image](https://github.com/user-attachments/assets/d8ade00c-c025-4836-92bb-b6a82dc74385)
![image](https://github.com/user-attachments/assets/ddc0ec78-cafd-41f4-8742-f9e403f956f3)
导入后拖拽后就散开了
![scene](https://github.com/user-attachments/assets/b9457cfc-016e-48fc-a5a6-20802538907c)

**Comment by more-strive** [comment]
这里是在导入解析时把所有元素都按单个元素添加进画布了，可以在导入的时候新建一个组把所有元素加到组内，就不会散开了
