### ISSUE TITLE
红色出血线的位置bug

### ISSUE THREAD

**Issue by ouyoungs** [dromara/yft-design#13]
![Snipaste_2023-11-29_12-17-30](https://github.com/dromara/yft-design/assets/53481783/8424a597-faa2-4fe0-aae8-b4d3cf8601e8)

右侧、下侧的线紧挨着画板了。

**Comment by more-strive** [comment]
[已更新](https://github.com/dromara/yft-design/commit/7548e32010853b9fd6391a2675726ef488b2d9b9)

**Comment by more-strive** [comment]
已更新
