### ISSUE TITLE
元素画布超出区域可见性

### ISSUE THREAD

**Issue by ouyoungs** [dromara/yft-design#14]
当元素拖出画布区域后，应该表现为：看不到元素但可以展示控制条。现在超出画布也会完整可见。

![Snipaste_2023-11-29_12-19-35](https://github.com/dromara/yft-design/assets/53481783/4588c761-28b0-4f36-955c-01644e1c7e71)

**Comment by more-strive** [comment]
这个在之前的main分支是有的，我是通过在画布中间套一个回型的path把超出的元素覆盖住

**Comment by more-strive** [comment]
beta12分支已更新
