### ISSUE TITLE
There may be issues with selecting multiple coordinates

### ISSUE THREAD

**Issue by zasulen** [dromara/yft-design#17]
![图片_20231215104128](https://github.com/dromara/yft-design/assets/128308093/7dfa498a-db7a-4d6f-ba6f-c19ef793c634)

**Comment by more-strive** [comment]
Thank you for your question. I will fix it as soon as possible

**Comment by more-strive** [comment]
When you select multiple objects, the ruler will not be displayed as one object. Only after combining and synthesizing, there is no logical problem and it will not be fixed
