### ISSUE TITLE
Will reference lines be supported in the future

### ISSUE THREAD

**Issue by zasusan** [dromara/yft-design#20]
such as pulling them out from the coordinate axis，Similar to the reference line in ps
![Snipaste_2023-12-25_17-13-32](https://github.com/dromara/yft-design/assets/128308093/960767d8-b9a3-4d97-a2a1-8efd1a7a81b9)

**Comment by more-strive** [comment]
It's a good question, I will support it in the future

**Comment by Aln6x5** [comment]
Can you provide your wechat? I want to discuss this project directly.

**Comment by more-strive** [comment]
> 你能提供你的微信吗？我想直接讨论这个项目。

15972699417

**Comment by more-strive** [comment]
已更新
