### ISSUE TITLE
Set width height unit cm to px error

### ISSUE THREAD

**Issue by Aln6x5** [dromara/yft-design#22]
Set width height unit cm to px will cause an error of not being able to use zoom

**Comment by more-strive** [comment]
update [https://githubfast.com/dromara/yft-design/commit/17f44bdcdaa3b45d7bf7d97c2c0898a46f33562d](https://githubfast.com/dromara/yft-design/commit/17f44bdcdaa3b45d7bf7d97c2c0898a46f33562d)
