### ISSUE TITLE
support for importing pdf to fabric

### ISSUE THREAD

**Issue by Pablituuu** [dromara/yft-design#23]
Hello, sorry, I'm currently doing a personal project where I'm trying to import pdf to fabric, I see that you have been able to do it, I already managed to import all this, but when the texts are transferred to fabric, the positions are broken, they appear anywhere except where they should be.

How did you achieve this, sorry?
Do you have some reference libraries?

**Comment by more-strive** [comment]
`pymupdf` You can take a look at this
