### ISSUE TITLE
为什么绘制一条直线会有红色和绿色的线存在？

### ISSUE THREAD

**Issue by hopkinson** [dromara/yft-design#24]

**Comment by hopkinson** [comment]
而且我无论选哪一个线，好像都是一条红色的箭头直线和一条绿色的直线重叠

**Comment by more-strive** [comment]
通过polygon来做的线段，功能还没完善，一个是带有箭头的线段，一个是没有箭头的线段，Line在画布中拖拽，移动都是当作一个元素操作，暂时没办法做到限位点操作，还在持续优化中

**Comment by more-strive** [comment]
> 而且我无论选哪一个线，好像都是一条红色的箭头直线和一条绿色的直线重叠

这里是创建了两个元素

**Comment by hopkinson** [comment]
明白，回复很及时。赞

**Comment by more-strive** [comment]
基础线段已经更新，曲线还未更新
