### ISSUE TITLE
我将你的项目合并到我的项目中，在构建时，我收到如图所示的错误，但它没有显示任何错误，所以即使我运行本地主机，我也无法构建它。

### ISSUE THREAD

**Issue by daicici** [dromara/yft-design#25]
方便沟通请联系telegram@Daicici
![issue](https://github.com/dromara/yft-design/assets/92419330/e36f29f8-0e62-47cc-a875-b3429e87976c)

**Comment by more-strive** [comment]
是用什么方式引入的？这是一个单独的项目，可以通过iframe的方式引入到您的项目中

**Comment by daicici** [comment]
我添加到vue3项目

**Comment by daicici** [comment]
如果你单独构建的话是可以的，错误可能是因为你命名的部分文件是中文的，你能把所有文件重命名为英文吗？

**Comment by more-strive** [comment]
> 如果你单独构建的话是可以的，错误可能是因为你命名的部分文件是中文的，你能把所有文件重命名为英文吗？

可能是字体文件哈，您可以把这些字体文件重命名哈
![image](https://github.com/dromara/yft-design/assets/113762408/c3c11b44-98c9-4d62-b205-ee6a136f442f)

**Comment by daicici** [comment]
对了

**Comment by daicici** [comment]
这样编辑时，您必须更正所有导入它们的位置

**Comment by daicici** [comment]
我认为，你的项目不应该有汉字来创建通用结构

**Comment by more-strive** [comment]
![Uploading image.png…]()
您这边有需要可以先自行修改下，现在还没精力做i18n的多语言的功能  
也欢迎您pr！

**Comment by more-strive** [comment]
没有问题我就关闭了哈
