### ISSUE TITLE
How to create Ruler and Guide line in v6.beta

### ISSUE THREAD

**Issue by minhnguyendev2002** [dromara/yft-design#26]
Hello developer
I'm having problems implementing rulers and guides on v6 where I can't import some necessary modules and classes. Please help me.

**Comment by more-strive** [comment]
What is your question?   
The rules and guides have already been implemented in the demo

**Comment by minhnguyendev2002** [comment]
Sorry that my question is not clear
I want to create guide line when I drag the ruler down and have a checkered background
![Screenshot 2024-02-05 093137](https://github.com/dromara/yft-design/assets/85899672/dd105438-5f54-465b-8182-27df0cef780c)

**Comment by more-strive** [comment]
Checked background already exists, but it is not open
#20  
This feature is currently under development

**Comment by minhnguyendev2002** [comment]
Yes, can I develop it and add it to your project?
and when I drag the mouse from the ruler, this error appears. Can you help me how to register a new class? Guide line class
![Screenshot 2024-02-05 094100](https://github.com/dromara/yft-design/assets/85899672/93e71838-b8f5-4f76-8b10-a48e3b1cd1a2)

**Comment by more-strive** [comment]
![image](https://github.com/dromara/yft-design/assets/113762408/99f6b603-12a6-49fd-9ecb-4a3edf4baad8)
You can register here, I may not be able to achieve it until later

**Comment by minhnguyendev2002** [comment]
thank sir
I was able to add a ruler, but my error now is, once I have added a ruler element, when I hover and move other elements and when I want to add a new ruler element, it crashes. error, please see my code and bugs
![image](https://github.com/dromara/yft-design/assets/85899672/f438165b-4271-4f69-9a5a-3fa5a2626514)
![image](https://github.com/dromara/yft-design/assets/85899672/ab5f4475-9fe2-4e5b-994c-1d4bb047cb54)
![image](https://github.com/dromara/yft-design/assets/85899672/44b0d6bb-874a-48ce-9f27-26a4928bb890)
![localhost_4000_design - Google Chrome 2024-02-20 11-43-19](https://github.com/dromara/yft-design/assets/85899672/8a3de576-f661-4d4e-884b-56ff8204b375)

Looking forward to receiving your help

**Comment by more-strive** [comment]
There was no error in the demo console. It will create many vertical lines, indicating that they have been successfully created

**Comment by more-strive** [comment]
See the demo console without any errors

**Comment by minhnguyendev2002** [comment]
That's exactly the problem I'm having, do you have any ideas.
The error here is that every time I perform an action (mouse move, click, etc.), a guide line is created when I click on the ruler
for example in my photo

**Comment by more-strive** [comment]
There is currently no good solution. You can submit a PR and I will study it later

**Comment by minhnguyendev2002** [comment]
hey bro, the white broad, how do i change its size when start
![image](https://github.com/dromara/yft-design/assets/85899672/cfc133ae-c46d-495c-8f1f-889637851203)

**Comment by more-strive** [comment]
There is a template file in the mocks file directory that contains JSON data serialized by fabric.js

**Comment by minhnguyendev2002** [comment]
yah, I changed the size in the template array, but the whiteboard doesn't cover the entire area I want and the size in the right corner is wrong.
![image](https://github.com/dromara/yft-design/assets/85899672/73b3485c-d2e4-491a-9daa-756950ddc9df)

**Comment by more-strive** [comment]
Can you create a new issue

**Comment by minhnguyendev2002** [comment]
Do you have any discord or methods for the community to communicate?

**Comment by more-strive** [comment]
![image](https://github.com/dromara/yft-design/assets/113762408/d8d9f307-40fd-4499-bf4b-19a65f40822f)
You can modify this parameter and try it out

**Comment by more-strive** [comment]
Updated
