### ISSUE TITLE
导出svg时，环形文字效果丢失，图片信息丢失

### ISSUE THREAD

**Issue by zjc2233** [dromara/yft-design#38]
定制画面
![image](https://github.com/dromara/yft-design/assets/43945226/95b133e7-b18d-49f3-a99b-4bd9c2252157)
![image](https://github.com/dromara/yft-design/assets/43945226/c34c5fed-4782-41e9-a4c5-825d5a73ff18)
<img width="185" alt="image" src="https://github.com/dromara/yft-design/assets/43945226/775f481b-bdc8-4f29-8e3a-dc093ab17bc2">

**Comment by more-strive** [comment]
已更新
