### ISSUE TITLE
代理地址为https://yft.design，导出pdf的时候，服务端报500

### ISSUE THREAD

**Issue by zjc2233** [dromara/yft-design#39]
![image](https://github.com/dromara/yft-design/assets/43945226/3977b7db-b77e-4167-a377-d416b9c53458)
<img width="709" alt="image" src="https://github.com/dromara/yft-design/assets/43945226/30cd50cc-3546-4f2d-88f0-fa7b324fb8a7">

**Comment by more-strive** [comment]
已新增代理接口
