### ISSUE TITLE
PDF import logic from API documentation.

### ISSUE THREAD

**Issue by minhnguyendev2002** [dromara/yft-design#55]
Hello developers, may I know how to make the server process the PDF file and return the arraylist in your document.
Are there any documents?
We look forward to receiving your support.
Thanks a lot.
![image](https://github.com/dromara/yft-design/assets/85899672/8452f40a-7105-46c5-90de-dd48f632b483)
![image](https://github.com/dromara/yft-design/assets/85899672/640ec037-606e-4154-9ee6-cf357c25ac0c)

**Comment by more-strive** [comment]
The server code is not open source and supports payment. Please contact us by email 15972699417@163.com
