### ISSUE TITLE
[Bug] 火狐Firefox浏览器兼容问题

### ISSUE THREAD

**Issue by ouyoungs** [dromara/yft-design#63]
![Snipaste_2024-04-02_00-09-14](https://github.com/dromara/yft-design/assets/53481783/84ca23d3-d022-4675-a239-2fa08a205111)

在火狐浏览器中，选中一个项目之后， 该项目会一直跟随鼠标。

**Comment by more-strive** [comment]
谢谢您的反馈，我们会即时修复

**Comment by more-strive** [comment]
已修复
