### ISSUE TITLE
【Bug】渲染PDF出错

### ISSUE THREAD

**Issue by louiesun** [dromara/yft-design#69]
[PDF](https://www.jianguoyun.com/p/DRQtzGcQi5DCCRiO-MkF)
效果：旋转失效，渐变消失。
![now](https://s3.bmp.ovh/imgs/2024/04/04/77d040cb78678696.png)

感觉修好了都可以做PDF编辑器了

**Comment by more-strive** [comment]
![image](https://github.com/dromara/yft-design/assets/113762408/cc0952c5-d657-42c6-986e-cbf7fdc06d9e)
已修复旋转和未解析的图片，文本
