### ISSUE TITLE
修改画布尺寸，所有的画布尺寸也会被修改

### ISSUE THREAD

**Issue by marysyy1101** [dromara/yft-design#71]
如题
![image](https://github.com/dromara/yft-design/assets/31183635/35bc51dc-8355-4aa4-b5ce-d897a5e9b83c)

**Comment by more-strive** [comment]
理论上缩略图显示的都是同一尺寸的模板，比如名片的正反面，所以修改尺寸是对同一类型的修改，这里暂不做修改
