### ISSUE TITLE
能封装成组件形式吗类似这样，便于项目中引用。

### ISSUE THREAD

**Issue by ijry** [dromara/yft-design#73]
https://github.com/pipipi-pikachu/PPTist/pull/249

**Comment by more-strive** [comment]
我这个项目就是基于pptist改的，看你也提交了pptist组件代码，你可以自己封装哈

**Comment by ijry** [comment]
pptist不合并我的提交，后边就没法保持同步更新了，所以需要官方库支持才行。

**Comment by more-strive** [comment]
组件的场景应用多嘛，iframe更适合吧，后面肯定是会router分首页和编辑器的

**Comment by ijry** [comment]
组件方便集成进别的项目，iframe我试过效果很差。https://mind.lingyun.net里面的草图使用的组件时React的只能用iframe，效果就很差，有个很明显的延迟加载。

**Comment by more-strive** [comment]
我看打开pptist还蛮快的，组件可能需要您自己维护了，不过后期我这边也会更新支持ppt格式的文档，欢迎持续关注哈
