### ISSUE TITLE
实时获取元素的坐标和宽高

### ISSUE THREAD

**Issue by yiyou1992** [dromara/yft-design#8]
作者你好，我想实时获取元素（文本、图片）的基于白色画板左上角的坐标和元素的宽高，请问怎么获取呢？

**Comment by more-strive** [comment]
在Editor/CanvasRight/index.vue有位置显示，可以把注释解开看看；
获取相对位置坐标是通过每个元素的坐标减去画板的坐标

**Comment by yiyou1992** [comment]
我解开注释看了。位置模块是空白的。

**Comment by more-strive** [comment]
这个需要你自己实现了，好像是被删除了吧

**Comment by more-strive** [comment]
https://githubfast.com/dromara/yft-design/commit/fb323f7c055ae01d86dd88a5e6b52f9ff27ff454

**Comment by more-strive** [comment]
[已更新](https://githubfast.com/dromara/yft-design/commit/fb323f7c055ae01d86dd88a5e6b52f9ff27ff454)
