### ISSUE TITLE
PSD解析渲染的技术

### ISSUE THREAD

**Issue by outongOwen** [dromara/yft-design#81]
我没有搞懂PSD解析渲染的逻辑和相关结束有哪些呀？大佬可以分享一下吗？

**Comment by more-strive** [comment]
是通过后端代码把psd文件解析成了json格式

**Comment by outongOwen** [comment]
这个有没有源码呢！可以让我学习一下吗？
---- 回复的原邮件 ----
***@***.***>发送日期2024年05月06日 19:48 ***@***.***> ***@***.***>,
***@***.***>主题Re: [dromara/yft-design] PSD解析渲染的技术 (Issue #81)
是通过后端代码把psd文件解析成了json格式

**Comment by more-strive** [comment]
加我微信吧
