### ISSUE TITLE
怎么自定义图层名字？

### ISSUE THREAD

**Issue by tanhh326** [dromara/yft-design#88]

**Comment by tanhh326** [comment]
> 不清楚您这里的具体需求啊，现在的图纸名字显示的字段layer

就是给每个图层加唯一标识，用你这个构建出json，然后别的地方批量替换出图啥的

**Comment by tanhh326** [comment]
额，我的意思是编辑器不支持

![image](https://github.com/dromara/yft-design/assets/82007768/a030f5a7-2798-4253-9f80-5ab901038ca7)

**Comment by more-strive** [comment]
更新了
